services:
  web-app:
    container_name: web-public-website
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "3034:3034"
    env_file:
      - .env
    restart: always
