import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/General/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <>
      <Navbar />
    <html lang="en">
      <body className={'antialiased px-4 md:px-8'}>
        {children}
      </body>
    </html>
    </>
  );
}
