import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/General/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={'antialiased px-4 md:px-8'}>
        <Navbar />
        <div className="flex flex-col max-w-[2000px] mx-auto pt-32 md:pt-40 pb-20 min-h-screen">
          {children}
        </div>
        </div>
      </body>
    </html>
  );
}
