import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/General/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased relative bg-charcoal">
        <Navbar />

        {/* Starfield overlay */}
        <div className="absolute inset-0 pointer-events-none">
          {Array.from({ length: 200 }).map((_, i) => {
            const size = Math.random() * 4 + 1;

            return (
              <div
              key={i}
              className="bg-cloud-white rounded-full"
              style={{
                width: `${size}px`,
                height: `${size}px`,
                top: `${Math.random() * 100}%`,
                left: `${Math.random() * 100}%`,
                position: "absolute",
              }}
            />
            )
          })}
        </div>

        {/* Main content */}
        <div className="relative flex flex-col mx-auto pb-20 min-h-screen gap-20 md:gap-40 z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
